# Name of website
title: Pomodoro Musei di Pesaro

# Your name to show in the footer
author: Francesco Rombaldoni

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Il progetto: "aboutus"
  Risorse:
    - GitHub: "https://github.com/Pomodoro-Musei-di-Pesaro"

################
# --- Logo --- #
################

avatar: "/assets/img/Logo.png"

round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "f.rombaldoni@campus.uniurb.it"
  github: Pomodoro-Musei-di-Pesaro 

rss-description: Pomodoro Musei di Pesaro

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: true

url-pretty: "https://github.com/Pomodoro-Musei-di-Pesaro"
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: false
navbar-var-length: false

######################################
# --- Colours / background image --- #
######################################

# I vecchi parametri colore sono stati rimossi per usare CSS custom properties e supporto light/dark automatico

#################################
# --- Web Analytics Section --- #
#################################

####################
# --- Comments --- #
####################

################
# --- Misc --- #
################

date_format: "%B %-d, %Y"

timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - LICENSE
  - README.md
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap